### ISSUE TITLE
Anki Leaderboard: Option to hide rate and donate button doesn't work

### ISSUE THREAD

**Issue by katullo** [shigeyukey/my_addons#147]
<img width="238" alt="Image" src="https://github.com/user-attachments/assets/ca87c02d-d77b-49a7-9c42-33d16864c0a9" />

Toggling off the new switch has no effect. After toggling it off, if you reopen the Config pane it toggles back on.

**Comment by shigeyukey** [comment]
Thanks for reporting the problem, I fixed it and uploaded it.

**Comment by katullo** [comment]
I've updated to the latest version and it still doesn't work.

**Comment by shigeyukey** [comment]
Is it the leaderboard window or Anki's Home? Anki Home button is different option (It will be merged later).
Others -> Show Home buttons

**Comment by katullo** [comment]
Oh sorry, I meant the Anki Home page. The Leaderboard window's fine.

**Comment by shigeyukey** [comment]
Thanks for the feedback! if you have any other problems or requests feel free to contact me.
